### ISSUE TITLE
CreateOrganizationDialog.razor fails to build: RZ9986 on Placeholder's @@ escape in a component attribute

### ISSUE THREAD

**Issue by samatstariongroup** [mycelium-cmbse/mycelium-forge#122]
`dotnet build`/`dotnet publish` fails on `Mycelium.Forge` with:

```
Components\Pages\AccountSettings\Dialogs\CreateOrganizationDialog.razor(43,39): error RZ9986: Component attributes do not support complex content (mixed C# and markup). Attribute: 'Placeholder', text: 'e.g. @esa'
obj\Debug\net10.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Components\Pages\AccountSettings\Dialogs\CreateOrganizationDialog_razor.g.cs(399,100): error CS7036: There is no argument given that corresponds to the required parameter 'value' of 'RuntimeHelpers.TypeCheck<T>(T)'
```

## Root cause

`CreateOrganizationDialog.razor:43` sets a placeholder on a component (not a plain HTML element):

```razor
<BbInput Id="create-org-scope"
         Value="@(this.Scope)"
         ValueChanged="@(this.OnScopeChanged)"
         Placeholder="e.g. @@esa"
         Class="..."/>
```

`@@` is Razor's escape for a literal `@` (intended to render `e.g. @esa`). That escape is fine on a plain HTML element's attribute, but `BbInput` is a Blazor component, and component attributes only bind a single literal or a single expression - they don't support the same freeform mixed markup/code content plain HTML attributes do. The Razor compiler sees the escaped `@@` and treats the attribute as mixed C#/markup, which a component parameter can't accept, hence RZ9986 (and the resulting broken source-generated code trips CS7036 downstream).

Introduced in c079e9b ("Feat #40 Layout Navigation and System Wiring", #108) and reproduces identically on `development`.

## Fix

Avoid the `@@` escape inside a component attribute, e.g.:

```razor
Placeholder="@("e.g. @esa")"
```

or move the literal into a `const`/field and reference that.
